# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: gw.eks.layer7.broadcom.com
    image: caapim/gateway:9.4.00
    ports:
    - "8081:8080"
    - "8444:8443"
    - "8000:8000"
    volumes:
    - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
    - ./deployment/build/gateway/deployment-1.0.0.gw7:/opt/docker/rc.d/deployment.gw7
    #- ./AWS-SK/src/main/gateway/config/global-env.properties:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/global-env.properties
    - ./Enterprise/src/main/gateway/config/global-env.properties:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/global-env.properties
    - ./Enterprise/src/main/gateway/config/privateKeys:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/config/privateKeys
    #- ./Enterprise/src/main/gateway/config/certificates:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/certificates
    secrets:
    - source: license
      target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
      ENV.PRIVATE_KEY.ssl: '{ "keystore": "Generic", "algorithm": "RSA", "keyPassword": "7layer" }'
      ENV.CERTIFICATE.gw.eks.layer7.broadcom.com.client: '{
                      "verifyHostname" : false,
                      "trustedForSsl" : true,
                      "trustedAsSamlAttestingEntity" : true,
                      "trustAnchor" : true,
                      "revocationCheckingEnabled" : true,
                      "trustedForSigningClientCerts" : true,
                      "trustedForSigningServerCerts" : true,
                      "trustedAsSamlIssuer" : true
                      }'
      ENV.CERTIFICATE_FILE.gw.eks.layer7.broadcom.com.client.pem: |-
                        Bag Attributes
                            friendlyName: ssl
                            localKeyID: 2B 44 FB 30 67 BB A6 34 BA BB 24 DF 50 50 D9 F8 08 92 86 37 
                        subject=/CN=gw.eks.layer7.broadcom.com
                        issuer=/CN=gw.eks.layer7.broadcom.com
                        -----BEGIN CERTIFICATE-----
                        MIICxjCCAa4CCQD4I22vSzOjsjANBgkqhkiG9w0BAQsFADAlMSMwIQYDVQQDDBpn
                        dy5la3MubGF5ZXI3LmJyb2FkY29tLmNvbTAeFw0xOTA5MjcxODQzNTlaFw0yOTA5
                        MjQxODQzNTlaMCUxIzAhBgNVBAMMGmd3LmVrcy5sYXllcjcuYnJvYWRjb20uY29t
                        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuntjXn0pbEPzJ83Uh7e/
                        e6bFEnXoykpeMc8E/CuqiUGlOtirIvgRBEmMeCprBdLajMOnNEqREzsVDgroNnfZ
                        Z6EFDp+6bwpGH0bflzLs/Q/ZVBqoYI9ItK/KxQZ/zq89Jeqfbz/i72rSrwSooclf
                        IlEGLGlsMym96wAt7Q6GYJ9VpECUp4EAo5wl0JRRWtm4ysCU/jRz5niHoqiDKmzq
                        ANUbrk+ty9rEChlIwla9p4fcDBWNzIZ9RN9kacpeDathXQcyxBgML18KY2RwwsYT
                        Hc8Gts2A4IJTHwcRyvAHNxMdsf73ZZl6zJ9iOgskPCoJgSnSd0995WI8pvWOOUbg
                        jQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCg9o1d9pWj4RPeMe9k378OL0KyPeN5
                        YBWD6MUU4cQo+GKqKh8cmaaU9Fw726q9FKrF+vUiPMrIda0gsJM1O/Bv8Qpx6wqj
                        Jp/zowY6m8p3TG1Zizhgma9ZgqjsNJKpofp/XhyvRDYlLq8dKASpPpkbkN76HpyM
                        M7cv1dZqm+TTeLjY/9uMwlmZWqb64FRk8JxG+OL6zEvDIOKtAq8S8GfwFGU6lr1p
                        F/X+nOZN7NJ3S+U3QJcugnaXXtOOqskEgUsD1AguUMdGotBu+f/Elvw66n8LrPet
                        wBDj8wiu2/C/eUVH+pKzAhiG+uSz+4fNeA8CIcsPlg+6pHA9s+XSxcgt
                        -----END CERTIFICATE-----

secrets:
  license:
    file: ./docker/license.xml
